import { PutObjectCommand } from "@aws-sdk/client-s3";
import { getS3Client } from "../../lib/s3Client";

// Config JSONs generated by /api/generate-json land here, under the bucket
// configured via S3_BUCKET_NAME.
const DEFAULT_PREFIX = "ZDH_AI_AGENT";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ success: false, message: "Method not allowed." });
  }

  const { json, fileName } = req.body || {};

  if (!json || typeof json !== "object") {
    return res.status(400).json({ success: false, message: "No JSON payload provided." });
  }

  const bucket = process.env.S3_BUCKET_NAME;
  if (!bucket) {
    return res.status(500).json({
      success: false,
      message: "S3_BUCKET_NAME isn't set on the server yet — add it to your environment variables.",
    });
  }

  const prefix = (process.env.S3_UPLOAD_PREFIX || DEFAULT_PREFIX).replace(/^\/+|\/+$/g, "");
  const baseName = (fileName || json.name || "config").trim().replace(/\.[^/.]+$/, "");
  const key = `${prefix}/${baseName}.json`;

  try {
    const client = getS3Client();
    await client.send(
      new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body: JSON.stringify(json, null, 2),
        ContentType: "application/json",
      })
    );

    return res.status(200).json({
      success: true,
      bucket,
      key,
      path: `s3://${bucket}/${key}`,
    });
  } catch (err) {
    const status = err?.$metadata?.httpStatusCode || 500;
    return res.status(status).json({
      success: false,
      message: err.message || "Couldn't upload the JSON to S3.",
    });
  }
}
